In [1]:
import numpy as np
import tkinter as tk # GUI

In [55]:
class TicTacToe:
    def __init__(self):
        self.reset()
        
    def reset(self):
        self.state = np.zeros(9, dtype=int)
        self.over = False
        self.turn = -1 # start with the human player
        
    def step(self, pos):
        if (self.state[pos] != 0):
            # position already filled
            print("That move is illegal!")
            return False
        self.state[pos] = self.turn
        
        # check if move made win
        if (game.isWinner()):
            print("Winner!")
        
        if (self.turn == -1):
            # switch to AI
            self.turn = 1
        else:
            # switch to human
            self.turn = -1
    
    def isWinner(self):
        for i in range(3):
            # horizontal
            if all([x == self.turn for x in self.state[3*i:3*i+3]]):
                return True
            # vertical
            if all([x == self.turn for x in [self.state[i], self.state[i+3], self.state[i+6]]]):
                return True
            # negative slope diagonal
            if all([x == self.turn for x in [self.state[0], self.state[4], self.state[8]]]):
                return True
            # positive slope diagonal
            if all([x == self.turn for x in [self.state[2], self.state[4], self.state[6]]]):
                return True
            
            return False # no winner
            
    def printBoard(self):
        print(self.state.reshape(3, 3))
    
        

In [56]:
if __name__ == '__main__':
    game = TicTacToe()

Winner!
[[-1  1  1]
 [ 0 -1  0]
 [ 0  0 -1]]
