In [1]:
import numpy as np
import tkinter as tk # GUI
import math

In [55]:
class TicTacToe:
    def __init__(self):
        self.reset()
        
    def reset(self):
        self.state = np.zeros(9, dtype=int)
        self.over = False
        self.turn = -1 # start with the human player
        
    def isWinner(self):
        s = self.state
        for i in range(3):
            # horizontal
            if all([x == self.turn for x in s[3*i:3*i+3]]):
                return True
            # vertical
            if all([x == self.turn for x in [s[i], s[i+3], s[i+6]]]):
                return True
            # negative slope diagonal
            if all([x == self.turn for x in [s[0], s[4], s[8]]]):
                return True
            # positive slope diagonal
            if all([x == self.turn for x in [s[2], s[4], s[6]]]):
                return True

            return False # no winner
    
    # helper function for evaluating score of a game state
    # RETURNS: score of a 3-element window in a game state
    def evaluateWindow(self, window):
        score = 0
        numPlayer = window.count(self.turn)
        numOpp = window.count(-self.turn)
        numEmpty = window.count(0)
        
        if numPlayer == 3:
            # bro just won, this is the branch to go to
            score += 100
        
        else if (numPlayer == 2 and numEmpty == 1):
            # bro is about to win
            score += 10
        
        else if (numPlayer == 1 and numEmpty == 2):
            score += 2
        
        else if (numOpponent == 2 and numEmpty == 1):
            # bro is about to lose, don't go here
            score -= 5
        
        return score
            
    
    # evaluates score of a player in current game state
    # RETURNS: 
        # positive if player is winning
        # negative if player is losing
        # 0 if draw
    def evaluateState(self):
        s = self.state
        
        for pos in range(3):
            # score of horizontals
            score += evaluateWindow(s[3*pos:3*pos+3])
            # score of verticals
            score += evaluateWindow([s[i], s[pos+3], s[pos+6]])
            # score of diagonals
            score += evaluateWindow([s[0], s[4], s[8]])
            score += evaluateWindow([s[2], s[4], s[6]])
        
        return score
        
    
    def isTerminatingNode(self):
        return self.state.isWinner()
    
    # will go through all game states since game is only 3x3
    def minimax(self, state, maximizingPlayer):
        # if terminating node:
        # TERMINATING: board is full or win has occurred
        # RETURN heuristic value of node
        if (all([x != 0 for x in state]) or checkWin())
        
        # maximizing player, AI
        if maximizingPlayer:
            value = -math.infinity
            for child in range(3):
                
                
        # minimizing player, human
        else:
            value = math.infinity
        
        
    def step(self, pos):
        if (self.state[pos] != 0):
            # position already filled
            print("That move is illegal!")
            return False
        self.state[pos] = self.turn
        
        if (self.turn == -1):
            # switch to AI
            self.turn = 1
        else:
            # switch to human
            self.turn = -1
                
    def printBoard(self):
        print(self.state.reshape(3, 3))
    
        

In [56]:
if __name__ == '__main__':
    game = TicTacToe()
    

Winner!
[[-1  1  1]
 [ 0 -1  0]
 [ 0  0 -1]]
