In [7]:
import numpy as np
import tkinter as tk # GUI
import math

### AI Evaluation
There are two evaluation functions we can implement in our AI via the minimax algorithm:
1. Score based on win, lose, or draw
2. Score based on number of connections that can be made  

Since this game is fairly simple (just a 3x3 board), we will use the first evaluation method

In [8]:
class TicTacToe:
    def __init__(self):
        self.reset()
        
    def reset(self):
        self.state = np.zeros(9, dtype=int)
        self.turn = -1 # start with player
        
    def isWinner(self, player):
        s = self.state
        for i in range(3):
            # horizontal
            if all([x == player for x in s[3*i:3*i+3]]):
                return True
            # vertical
            if all([x == player for x in [s[i], s[i+3], s[i+6]]]):
                return True
            # negative slope diagonal
            if all([x == player for x in [s[0], s[4], s[8]]]):
                return True
            # positive slope diagonal
            if all([x == player for x in [s[2], s[4], s[6]]]):
                return True

        return False # no winner
        
    # Does the current game state in game tree lead to a win or a draw?
    def isTerminatingNode(self):
        return self.isWinner(-1) or self.isWinner(1) or all([x != 0 for x in self.state]) 
    
    def evaluate(self):
        # AI wins
        if self.isWinner(1):
            return 100
        # AI loses
        elif self.isWinner(-1):
            return -100
        # draw
        elif all([x != 0 for x in self.state]):
            return 0
    
    # will go through all game states since game is only 3x3
    # AI to act as maximizing player
    def minimax(self, maximizingPlayer):
        # if terminating node:
        # TERMINATING: board is full or win has occurred
        # RETURN heuristic value of node
        if self.isTerminatingNode():
            return self.evaluate(), -1 # won't return the position
                
        if maximizingPlayer:
            maxValue = -np.inf
            for p in range(9):
                if self.isIllegalStep(p) == False:
                    # make move
                    self.step(p, 1)
                    value = self.minimax(False)[0]
                    # undo the move
                    self.state[p] = 0
                    if value > maxValue:
                        maxValue = value
                        maxPos = p

            return maxValue, maxPos
                    
        else:
            minValue = np.inf
            for p in range(9):
                if self.isIllegalStep(p) == False:
                    # make move
                    self.step(p, -1)
                    value = self.minimax(True)[0]
                    # undo the move
                    self.state[p] = 0
                    if value < minValue:
                        minValue = value
                        minPos = p
                        
            return minValue, minPos
        
        
    def isIllegalStep(self, pos):
        return self.state[pos] != 0 and pos >= 0 and pos < 9
    
    def step(self, pos, player):
        # position must be legal
        if self.isIllegalStep(pos):
            print("That move is illegal!")
            return False
        
        self.state[pos] = player
        self.turn = -self.turn
                        
    def printBoard(self):
        print(self.state.reshape(3, 3))
    
    # helper function for evaluating score of a game state
    # RETURNS: score of a 3-element window in a game state
#     def evaluateWindow(self, window):
#         score = 0
#         maxScore = 100
#         slotScore = 2
#         numPlayer = window.count(self.turn)
#         numOpp = window.count(-self.turn)
#         numEmpty = window.count(0)
        
#         if numPlayer == 3:
#             # bro just won, WE GO TO THIS PATH
#             score += maxScore
            
#         elif numPlayer == 2 and numEmpty == 1:
#             # two connections
#             score += slotScore * numPlayer
        
#         elif numPlayer == 1 and numEmpty == 2:
#             # one connection
#             score += slotScore * numPlayer
        
#         if numOpp == 2 and numEmpty == 1:
#             # bro is about to lose, WE DON'T DO THAT
#             score -= maxScore
               
#        return score
            
    
    # evaluates score of a player in current game state
    # RETURNS: 
        # positive if player is winning
        # negative if player is losing
        # 0 if draw
#     def evaluateState(self):
#         s = self.state
        
#         for pos in range(3):
#             # score of horizontals
#             score += evaluateWindow(s[3*pos:3*pos+3])
#             # score of verticals
#             score += evaluateWindow([s[i], s[pos+3], s[pos+6]])
#             # score of diagonals
#             score += evaluateWindow([s[0], s[4], s[8]])
#             score += evaluateWindow([s[2], s[4], s[6]])
        
#         return score    

In [9]:
if __name__ == '__main__':
    game = TicTacToe()
    while (not game.isTerminatingNode()):
        userPos = int(input("Pick position on the board (0-8): "))
        game.step(userPos, -1) # player makes move
        if (not game.isTerminatingNode()):
            aiMove = game.minimax(1)[1] # AI makes move
            print(f"AI made a move in position {aiMove}.")
            game.step(aiMove, 1)
        game.printBoard()
    
    if (game.isWinner(1) or game.isWinner(-1)):
        print(f"{'AI' if game.turn else 'Player'} won!")
        
    else:
        print("Draw. You and the AI are too smart.")

Pick position on the board (0-8): 2
AI made a move in position 4.
[[ 0  0 -1]
 [ 0  1  0]
 [ 0  0  0]]
Pick position on the board (0-8): 0
AI made a move in position 1.
[[-1  1 -1]
 [ 0  1  0]
 [ 0  0  0]]
Pick position on the board (0-8): 7
AI made a move in position 3.
[[-1  1 -1]
 [ 1  1  0]
 [ 0 -1  0]]
Pick position on the board (0-8): 5
AI made a move in position 8.
[[-1  1 -1]
 [ 1  1 -1]
 [ 0 -1  1]]
Pick position on the board (0-8): 6
[[-1  1 -1]
 [ 1  1 -1]
 [-1 -1  1]]
Draw. You and the AI are too smart.
